/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analytics': RouteRecordInfo<'/analytics', '/analytics', Record<never, never>, Record<never, never>>,
    '/analytics/': RouteRecordInfo<'/analytics/', '/analytics', Record<never, never>, Record<never, never>>,
    '/features': RouteRecordInfo<'/features', '/features', Record<never, never>, Record<never, never>>,
    '/retrospective/new': RouteRecordInfo<'/retrospective/new', '/retrospective/new', Record<never, never>, Record<never, never>>,
    '/retrospective/past': RouteRecordInfo<'/retrospective/past', '/retrospective/past', Record<never, never>, Record<never, never>>,
    '/retrospective/retro': RouteRecordInfo<'/retrospective/retro', '/retrospective/retro', Record<never, never>, Record<never, never>>,
    '/retrospective/templates': RouteRecordInfo<'/retrospective/templates', '/retrospective/templates', Record<never, never>, Record<never, never>>,
    '/team/': RouteRecordInfo<'/team/', '/team', Record<never, never>, Record<never, never>>,
    '/team-dashboard': RouteRecordInfo<'/team-dashboard', '/team-dashboard', Record<never, never>, Record<never, never>>,
    '/user/login': RouteRecordInfo<'/user/login', '/user/login', Record<never, never>, Record<never, never>>,
    '/user/register': RouteRecordInfo<'/user/register', '/user/register', Record<never, never>, Record<never, never>>,
  }
}
